# Generated by Django 3.0.6 on 2020-05-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=200)),
                ('hashed_name', models.CharField(max_length=200)),
                ('height', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('channel', models.IntegerField(default=0)),
                ('client_ip', models.CharField(max_length=200)),
                ('upload_dttm', models.DateTimeField(auto_now=True)),
                ('generated', models.BooleanField(default=False)),
            ],
        ),
    ]
