FROM nvidia/cuda:10.0-devel-ubuntu18.04

# opencv-devのインストール
RUN apt-get update -y && apt-get install -y \ 
    apt-utils python3-pip\
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# TensorflowとOpencvのインストール
RUN pip3 install --upgrade pip
RUN pip3 install numpy==1.16.4 tensorflow-gpu==1.14.0 keras

ENV APP_NAME keras_opencv
WORKDIR /home/$APP_NAME

