FROM nvidia/cuda:10.1-devel-ubuntu18.04

# opencv-devのインストール
RUN apt-get update -y && apt-get install -y \ 
    apt-utils python3-pip\
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# TensorflowとOpencvのインストール
RUN pip3 install --upgrade pip
RUN pip3 install setuptools==41.0.0 tensorflow==2.1.0 keras jupyter

ENV APP_NAME tf2_opencv
WORKDIR /home/$APP_NAME

