FROM tensorflow/tensorflow:latest-gpu-py3-jupyter

ENV DEBIAN_FRONTEND=noninteractive

# opencv-devのインストール
RUN apt-get update -y && apt-get install -y \ 
    libopencv-dev apt-utils python3-pip\
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# TensorflowとOpencvのインストール
RUN pip3 install opencv-python

ENV APP_NAME tf_opencv
WORKDIR /home/$APP_NAME

CMD [ '/bin/bash'  ]
