FROM tensorflow/tensorflow:latest-gpu-py3

RUN pip install --upgrade pip
RUN pip install keras jupyter responder peewee

ENV APP_NAME gpu
WORKDIR /home/$APP_NAME

# # ユーザーを作成
ARG UID=1000
RUN useradd -m -u ${UID} docker

# # # 作成したユーザーに切り替える
# # USER ${UID}
